# Generated by Django 5.2.1 on 2025-06-02 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('books', '教材书籍'), ('digital', '数码产品'), ('clothes', '服装鞋包'), ('daily', '日常用品'), ('sports', '运动健身'), ('others', '其他分类')], default='others', max_length=20, verbose_name='商品类别'),
        ),
    ]
